<?php

namespace AdactiveSas\Saml2BridgeBundle\Entity;


class HostedIdentityProvider extends IdentityProvider
{
    /**
     * @return string
     */
    public function getLoginUrl()
    {
        return $this->get('loginUrl');
    }

    /**
     * @return string
     */
    public function getLogoutUrl()
    {
        return $this->get('logoutUrl');
    }

    /**
     * @return bool
     */
    public function wantSignedAuthnRequest()
    {
        return $this->get("wantSignedAuthnRequest"); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function wantSignedLogoutRequest()
    {
        return $this->get("wantSignedLogoutRequest"); // TODO: Change the autogenerated stub
    }
}