<?php

namespace AdactiveSas\Saml2BridgeBundle\Entity;


class HostedIdentityProvider extends IdentityProvider
{
    /**
     * @return string
     */
    public function getLoginUrl()
    {
        return $this->get('loginUrl');
    }

    /**
     * @return string
     */
    public function getLogoutUrl()
    {
        return $this->get('logoutUrl');
    }

    /**
     * @return bool
     */
    public function mustSignedRequests()
    {
        return $this->get("must_signed_requests"); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function mustSignedResponses()
    {
        return $this->get("must_signed_responses"); // TODO: Change the autogenerated stub
    }
}