<?php

/**
 * Copyright (C) 2017 Adactive SAS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace AdactiveSas\Saml2BridgeBundle\Entity;


use AdactiveSas\Saml2BridgeBundle\SAML2\SAML2_Const;

class HostedIdentityProvider extends IdentityProvider
{
    /**
     * @return string
     */
    public function getLoginUrl()
    {
        return $this->get('loginUrl');
    }

    /**
     * @return string
     */
    public function getLogoutUrl()
    {
        return $this->get('logoutUrl');
    }

    /**
     * @return string
     */
    public function getAuthnContext(){
        return $this->get('authnContext', SAML2_Const::AC_UNSPECIFIED);
    }

    /**
     * @return bool
     */
    public function wantSignedAuthnRequest()
    {
        return $this->get("wantSignedAuthnRequest"); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function wantSignedLogoutRequest()
    {
        return $this->get("wantSignedLogoutRequest"); // TODO: Change the autogenerated stub
    }
}